### ISSUE TITLE
Stuck at the very first step of "reload project"

### ISSUE THREAD

**Issue by Amama-Fatima** [LBeghini/Hotel-Management-System#104]
Hey there!

I am an almost beginner programmer and am stuck at the very first step.

##'reload project'
I followed the instructions on the README.md file. One of the very first was:
>"Anywhere inside the IDE, type shift+shift and when the search input appears, type reload project and hit enter. This will install all Maven dependencies."

##Error
When I do that, a build tab opens in the bar below and shows a lot of errors:

com.lowagie:itext:pom:2.1.7.js7 failed to transfer from http://0.0.0.0/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of maven-default-http-blocker has elapsed or updates are forced. Original error: Could not transfer artifact com.lowagie:itext:pom:2.1.7.js7 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [jaspersoft-third-party (http://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts/, default, releases+snapshots), jr-ce-releases (http://jaspersoft.jfrog.io/jaspersoft/jr-ce-releases, default, releases+snapshots)]

Since Maven 3.8.1 http repositories are blocked.

Possible solutions:
- Check that Maven pom files do not contain http repository http://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts/
- Check that Maven pom files do not contain http repository http://jaspersoft.jfrog.io/jaspersoft/jr-ce-releases
- Add a mirror(s) for http://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts/, http://jaspersoft.jfrog.io/jaspersoft/jr-ce-releases that allows http url in the Maven settings.xml
- Downgrade Maven to version 3.8.1 or earlier in settings

I asked ChatGPT and none of the solutions it gave are working.
Kindly explain why my dependencies are not being downloaded and instead this error is being shown.

**Comment by predodamiao** [comment]
Hey, @Amama-Fatima!

First of all, nice to see you using our project for your studies!

I took a look at the project and I could reproduce the error here. After some analysis, I found out that the problem is related to lowagie dependency on Jasper Reports, which import inside its package.

As a faster solution, and as we import lowagie outside Jasper, you can exclude lowagie from Jasper. For this, make your `jasperreports` import on`pom.xml` like this:

```xml
        <dependency>
            <groupId>net.sf.jasperreports</groupId>
            <artifactId>jasperreports</artifactId>
            <version>6.13.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.lowagie</groupId>
                    <artifactId>itext</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

Anyway, as soon as possible, we gonna update the project to the latest versions of dependencies.

If you have any other problems, please don't hesitate to contact us.
